### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [engspa12/TravelDBM#1]
Hello Sir. I'm a Graphics Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design to improve visualization of your project as my Open Source Contribution?

Thanks for theattention.

**Comment by engspa12** [comment]
Hi Sir. I'm glad that you would like to help improve this project. I don't have any problem with your contribution Sir. By the way, I'm sorry for my late reply but these months I have been very busy at work.

Thank you for your time. I'm looking forward to hearing from you.

Regards

**Comment by anharismail** [comment]
Hi @engspa12 , Nice to hear any response from you. I'll provide my logo idea here as soon as possible.

**Comment by engspa12** [comment]
It sounds great Sr. Thank you again for your interest.

**Comment by anharismail** [comment]
Hi @engspa12 , I've designed a logo for this project. This logo concept inspired from hotel idea as your current icon.

Very welcome if you have any opinions or suggestions about it.

Regards.

![TravelDBM Ver  1](https://user-images.githubusercontent.com/37614260/61293543-26714500-a7fe-11e9-9a7f-fde8b60e9d19.png)

**Comment by engspa12** [comment]
Hello Sr,

The first logo looks great. To be completely honest, I'm not a designer so I don't exactly where to use this logo. Should I put it on the main screen of my app? or during a launch screen with animations? I really appreciate your contribution Sr. 

Thank you so much again for your time and interest.

Regards

**Comment by anharismail** [comment]
Hi @engspa12 . Thanks for your response.

Actually, it's not a different logo. It just black and white version. Because, a professional logo must have its black and white version. So, the first actually the main one.

You can use this logo in main screen, but you can also put it on launch (splash) screen with animation if you didn't have it before. I'll put any purpose version of this logo (like as icon) on your repository if you want.

Regards.

**Comment by anharismail** [comment]
If permitted, I've made a pull request about the logo.

I also provide all editable files here: https://drive.google.com/drive/u/1/folders/1LH2VRwuwQMhrtIfJustDw4slGKR70Olg

**Comment by engspa12** [comment]
Hello Sr,

I merged the pull request. Thank you. I think I will use it on the splash screen since it gives a better presentation of the app and also because it will help me with another application I'm working right now where material design is critical. So I will take this opportunity to test several types of transitions between activities.

As I said before, thank you so much for your assistance Sr. I'm really happy that you got interested in this project. Your contribution will definitely improve TravelDBM user interface.

By the way, I would like to ask you something else if you don't mind Sr. and it is how did you find my project exactly? Did you find it in my LinkedIn account or somewhere else?

I'm just curious and this information will be very important in the future because one of my long-term goals is becoming a freelancer. So if you could provide that info, I would appreciate it a lot.

Regards

**Comment by anharismail** [comment]
Hi @engspa12 . Thanks for using my logo and give the response for this proposal.

I get your repository just from searched manually on Github. Very nice if we can collaborate in your othe projects.

Regards.

**Comment by engspa12** [comment]
Hello Sr,

Of course, I don't have any problem if you want to contribute to any other of my projects. Any suggestions or commentaries are welcome as well. I will update this repository next weekend so it can showcase the logo on the splash screen. Thank you again for the resources.

Regards.

**Comment by engspa12** [comment]
The files have been updated. The logo looks amazing :)
